//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SfxFileName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SfxFileName() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tetris.SfxFileName", typeof(SfxFileName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ButtonClick.wav.
        /// </summary>
        public static string ButtonClick {
            get {
                return ResourceManager.GetString("ButtonClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearOne1.wav.
        /// </summary>
        public static string ClearOne1 {
            get {
                return ResourceManager.GetString("ClearOne1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearThree1.wav.
        /// </summary>
        public static string ClearThree1 {
            get {
                return ResourceManager.GetString("ClearThree1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClearTwo1.wav.
        /// </summary>
        public static string ClearTwo1 {
            get {
                return ResourceManager.GetString("ClearTwo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CountDown.wav.
        /// </summary>
        public static string CountDown {
            get {
                return ResourceManager.GetString("CountDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameOver.wav.
        /// </summary>
        public static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameOverHighScore.wav.
        /// </summary>
        public static string GameOverHighScore {
            get {
                return ResourceManager.GetString("GameOverHighScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameStart.wav.
        /// </summary>
        public static string GameStart {
            get {
                return ResourceManager.GetString("GameStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlayerAction.wav.
        /// </summary>
        public static string PlayerAction {
            get {
                return ResourceManager.GetString("PlayerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetris1.wav.
        /// </summary>
        public static string Tetris1 {
            get {
                return ResourceManager.GetString("Tetris1", resourceCulture);
            }
        }
    }
}
